spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://keycloak.openlearnhub.io.vn/realms/OpenLearnHub/protocol/openid-connect/certs
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:hieunm123.ptit@gmail.com}
    password: ${MAIL_PASSWORD:yznf hkso oswy ufmx}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${MAIL_STARTTLS_ENABLE:true}
          ssl:
            trust: ${MAIL_SSL_TRUST:smtp.gmail.com}

  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/smart_feed?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

  messages:
    basename: i18n/messages
    encoding: UTF-8
    fallback-to-system-locale: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

keycloak:
  clientId: open-learn-hub
  clientSecret: RSytCO0s3kqV2EHLyZD0Yc7BbGfDpxpb
  serverUrl: https://keycloak.openlearnhub.io.vn/
  realm: OpenLearnHub

authorization:
  server:
    url: https://keycloak.openlearnhub.io.vn/realms/OpenLearnHub/protocol/openid-connect/auth

token:
  server:
    url: https://keycloak.openlearnhub.io.vn/realms/OpenLearnHub/protocol/openid-connect/token

policy:
  enforce: "/policy-enforcer.json"

auth:
  server:
    url: https://user.service.openlearnhub.io.vn/

gemini:
  api:
    key: AIzaSyCbAIe1WT9x9_40dv_jkTLgrsTXyKBHJDM
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent


